language: node_js
node_js:
  - '12'
dist: xenial
os: linux
cache:
  - yarn: true

install:
  - yarn install

branches:
  only:
    - master
    - develop
    - mastercopy

script:
  - echo "PR number:${TRAVIS_PULL_REQUEST}"
  - ./test.sh

after_success:
  - echo "$TRAVIS_BRANCH"
  - echo "$TRAVIS_PULL_REQUEST"
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" ]; then 
      ./triggerSanity.sh;
    fi 
