language: node_js
node_js:
  - '12'
dist: xenial
os: linux
cache:
  - yarn: true

install:
  - yarn install

branches:
  only:
    - master
    - develop

script:
  - yarn run fail

# jobs:
#   allow_failures:
#     - stage: Test
#   include:
#     - stage: Test on master       
#       script: 
#         - ./test.sh master
#       env: TestMaster 
#     - stage: Test on develop
#       script:
#         - ./test.sh develop
#       env: TestDevelop
#     - stage: Test
#       script:
#         - echo "test that always run"
#       env: TestThatAlwaysRun
#     - script:
#         - echo "test that always run 2"
#       env: Test that always run 2
#     - stage: TestTriggeredByAPIonly
#       script:
#         - echo "test should only be triggered by API"
#       env: TestAPI


stages:
  - name: Test on master
    if: branch = master
  - name: Test on develop
    if: branch = develop
  - Test