language: node_js
node_js:
  - '12'
dist: xenial
os: linux
cache:
  - yarn: true

install:
  - yarn install

branches:
  only:
    - master
    - develop
    - mastercopy

script:
  - ./test.sh

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" ]]; then 
      ./triggerSanity.sh;
    fi
