language: node_js
node_js:
  - '12'
dist: xenial
os: linux
cache:
  - yarn: true

install:
  - yarn install

script:
  - echo "${TRAVIS_REPO_SLUG#*/}"
  - echo "$TRAVIS_BRANCH"
  - echo "$TRAVIS_PULL_REQUEST"
  - ./test.sh

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then echo "Triggering sanity test!!"; ./triggerSanity.sh; fi
