language: node_js
node_js:
  - '12'
dist: xenial
os: linux
cache:
  - yarn: true

install:
  - yarn install

branches:
  only:
    - master
    - develop
    - mastercopy

script:
  - chmod +x *.sh
  - ./test.sh
  - if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_PULL_REQUEST" != "false" ]]; then 
      ./triggerSanity.sh;
    fi

after_success:
  - echo "$TRAVIS_BRANCH"
  - echo "$TRAVIS_PULL_REQUEST"
