language: node_js
node_js:
  - '12'
dist: xenial
os: linux
cache:
  - yarn: true

install:
  - yarn install

branches:
  only:
    - master
    - develop

jobs:
  allow_failures:
    - stage: Test
  include:
    - stage: Test on master       
      script: 
        - ./test.sh master
      name: "test master" 
    - stage: Test on develop
      script:
        - ./test.sh develop
      name: "test develop"
    - stage: Test
      script:
        - echo "test that always run"
      name: "test that always run"
    - stage: Test triggered by API only
      script:
        - echo "test should only be triggered by API"
      env: testAPI



stages:
  - name: Test on master
    if: branch = master
  - name: Test on develop
    if: branch = develop
  - Test