language: node_js
node_js:
  - '12'
dist: xenial
os: linux
cache:
  - yarn: true

install:
  - yarn install

branches:
  only:
    - master
    - develop
    - mastercopy

jobs:
  allow_failures:
    - stage: Test
  include:
    - stage: Test on master       
      script: 
        - ./test.sh master
        - if [[ "$TRAVIS_BRANCH" == "master" ]]; then ./triggerBuild.sh; fi
      env: TestMaster
    - stage: Test on develop
      script:
        - ./test.sh develop
      env: TestDevelop
    - stage: Test
      script:
        - if [[ "$TRAVIS_BRANCH" == "mastercopy" && "$TRAVIS_PULL_REQUEST" == "false" ]]; then 
            echo "This is not a pull request build.";
          fi
        - echo "test that always run"
      env: TestThatAlwaysRun
    - stage: Test triggered by API only
      script:
        - echo "test should only be triggered by API"
      env: TestAPI

 
stages:
  - name: Test on master
    if: branch = master
  - name: Test on develop
    if: branch = develop
  - Test

notifications:
  webhooks: https://www.travis-ci.com/github/Stanliest/travis-build-stages/notifications